[package]
name = "meteora_sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
anchor-lang = { version = "0.30.0", optional = true }
borsh = "1.5.1"
kaigan = "0.2.5"
num-derive = "0.4"
num-traits = "^0.2"
serde = { version = "^1.0", features = ["derive"], optional = true }
serde_with = { version = "^3.0", optional = true }
solana-program = "^2.1.6"
solana-client = { version = "~1.18", optional = true }
solana-sdk = { version = "~1.18", optional = true }
thiserror = "^1.0"

[features]
anchor = ["dep:anchor-lang"]
anchor-idl-build = ["anchor", "anchor-lang?/idl-build"]
serde = ["dep:serde", "dep:serde_with"]
test-sbf = []
fetch = ["dep:solana-client", "dep:solana-sdk"]