[workspace]
members = ["crates/*", "examples/*"]
exclude = ["examples/streams-ts/"]
resolver = "2"

[workspace.dependencies]
yellowstone-grpc-client = { version = "2.0.0" }
yellowstone-grpc-proto = { version = "2.0.0", default-features = false }
yellowstone-vixen = { path = "crates/runtime", version = "0.2.0" }
yellowstone-vixen-core = { path = "crates/core", version = "0.2.0" }
yellowstone-vixen-mock = { path = "crates/mock", version = "0.2.0" }
yellowstone-vixen-parser = { path = "crates/parser", version = "0.2.0" }
yellowstone-vixen-proto = { path = "crates/proto", version = "0.2.0" }

yellowstone-vixen-meteora-parser = { path = "crates/meteora-parser", version = "0.1.0" }
yellowstone-vixen-pumpfun-parser = { path = "crates/pumpfun-parser", version = "0.1.0" }
yellowstone-vixen-jupiter-swap-parser = { path = "crates/jupiter-swap-parser", version = "0.1.0" }

# helps resolving zeroize dependency conflicts betweeen solana creates depending on curve25519-dalek and yellowstone-grpc 
# https://github.com/solana-labs/solana/issues/26688
zeroize = { version = "1.7", default-features = false }

[patch.crates-io]
curve25519-dalek = { git = "https://github.com/anza-xyz/curve25519-dalek.git", rev = "b500cdc2a920cd5bff9e2dd974d7b97349d61464" }
