name: yellowstone-vixen
services:
  prometheus-backend:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    command: ["--config.file=/etc/prometheus/prometheus-config.yaml"]
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  prometheus-pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"
  envoy:
    image: envoyproxy/envoy:dev-bc1de120b2f12188d7f21b444b7401b5a7ac6175
    ports:
      - "10000:10000"
    volumes:
      - ./envoy-config.yaml:/etc/envoy/envoy.yaml
    extra_hosts:
      - "host.docker.internal:host-gateway"