global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Solana Stream Processor metrics
  - job_name: 'solana-stream-processor'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Add more targets as needed
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']