name: Build yellowstone-vixen crates
# This workflow uses github runners.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# This may be adjusted to whatever suits best your runners config.
# Current config will build on manual trigger or pull-request (each push)
on:
  # pull_request can be removed, to save minutes on github runners
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-api:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
    # This can be also be runned on self-hosted github runners
    runs-on: ['${{ matrix.os }}']

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      # This step can be omited, to save storage space on the organization account
      # Build process will take longer
      - name: set build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            yellowstone-vixen/target/
          key: ${{ matrix.os }}_yellowstone_vixen_${{ hashFiles('yellowstone-vixen/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}_yellowstone_vixen

      - name: build yellowstone-vixen
        run: cargo build --verbose --release
